/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ActorDetailsPanel.java
 *
 * Created on Jul 19, 2009, 4:46:10 PM
 */

package gurpsinittool.ui;

import java.awt.Color;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

import gurpsinittool.app.*;
import gurpsinittool.data.Actor;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;

/**
 *
 * @author dcsmall
 */
public class ActorDetailsPanel extends javax.swing.JPanel 
	implements ListSelectionListener, TableModelListener{

	private static final boolean DEBUG = true;
	
	private InitTable initTable;
	private ActorTableModel actorModel;
	private boolean actorLoaded = false;
	private int selectedActor = -1;
	
    /** Creates new form ActorDetailsPanel */
    public ActorDetailsPanel(InitTable initTable) {
    	this.initTable = initTable;
    	this.actorModel= (ActorTableModel) initTable.getModel();
    	initTable.getSelectionModel().addListSelectionListener(this);
    	actorModel.addTableModelListener(this);

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        timers = new javax.swing.JPanel();
        add_timer = new javax.swing.JButton();
        attacks = new javax.swing.JPanel();
        add_attack = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        status = new javax.swing.JComboBox();
        type = new javax.swing.JComboBox();
        target = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        hp = new javax.swing.JFormattedTextField();
        damage = new javax.swing.JFormattedTextField();
        health = new javax.swing.JFormattedTextField();

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setText("Status:");

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel3.setText("Type:");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel4.setText("HP:");

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel5.setText("Damage:");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel6.setText("Target:");

        timers.setBorder(javax.swing.BorderFactory.createTitledBorder("Timers"));

        add_timer.setText("Add Timer");
        add_timer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_timerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timersLayout = new javax.swing.GroupLayout(timers);
        timers.setLayout(timersLayout);
        timersLayout.setHorizontalGroup(
            timersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timersLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(add_timer))
        );
        timersLayout.setVerticalGroup(
            timersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_timer))
        );

        attacks.setBorder(javax.swing.BorderFactory.createTitledBorder("Attacks"));

        add_attack.setText("Add Attack");
        add_attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_attackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout attacksLayout = new javax.swing.GroupLayout(attacks);
        attacks.setLayout(attacksLayout);
        attacksLayout.setHorizontalGroup(
            attacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attacksLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(add_attack))
        );
        attacksLayout.setVerticalGroup(
            attacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attacksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_attack))
        );

        name.setBackground(new java.awt.Color(236, 233, 216));
        name.setFont(name.getFont().deriveFont(name.getFont().getStyle() | java.awt.Font.BOLD, name.getFont().getSize()+9));
        name.setText("name");
        name.setBorder(null);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });

        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Waiting", "Disabled", "Unconscious", "Dead" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC", "Ally", "Enemy", "Neutral", "Special" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        target.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none" }));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel7.setText("Health:");

        hp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        hp.setText("99");
        hp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });
        hp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hpPropertyChange(evt);
            }
        });

        damage.setForeground(new java.awt.Color(220, 0, 0));
        damage.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        damage.setText("99");
        damage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });
        damage.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                damagePropertyChange(evt);
            }
        });

        health.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        health.setText("99");
        health.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });
        health.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                healthPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(health, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(damage, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(hp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(damage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(health, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_timerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_timerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_timerActionPerformed

    private void add_attackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_attackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_attackActionPerformed

    private void hpPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hpPropertyChange
        // TODO add your handling code here:
        if(actorLoaded && evt.getPropertyName().equals("value")) {
           	if (DEBUG) { System.out.println("HP Property change event (" + evt.getNewValue() + ") " + evt.getPropertyName() + ": " + evt.toString()); }
            actorModel.setValueAt(((Long) hp.getValue()).intValue(), selectedActor, ActorTableModel.columns.HP.ordinal());
        }
    }//GEN-LAST:event_hpPropertyChange

    private void damagePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_damagePropertyChange
        if(actorLoaded && evt.getPropertyName().equals("value")) {
        	actorModel.setValueAt(((Long) damage.getValue()).intValue(), selectedActor, ActorTableModel.columns.Damage.ordinal());
        }
    }//GEN-LAST:event_damagePropertyChange

    private void healthPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_healthPropertyChange
        if(actorLoaded && evt.getPropertyName().equals("value")) {
            actorModel.setValueAt(((Long) health.getValue()).intValue(), selectedActor, ActorTableModel.columns.Health.ordinal());
        }
    }//GEN-LAST:event_healthPropertyChange

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        if(actorLoaded) {
        	//String newValue = ((JComboBox)evt.getSource()).getSelectedItem().toString();
        	//String oldValue = actorModel.getActor(initTable.getSelectedRow()).State.toString();
            //if (!newValue.equals(oldValue)) {
        		if (DEBUG) { System.out.println("State action performed event " + evt.toString()); }
            	actorModel.setValueAt(((JComboBox)evt.getSource()).getSelectedItem().toString(), selectedActor, ActorTableModel.columns.State.ordinal());
            //}
        }
    }//GEN-LAST:event_statusActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        if(actorLoaded) {
        	//String newValue = ((JComboBox)evt.getSource()).getSelectedItem().toString();
        	//String oldValue = actorModel.getActor(initTable.getSelectedRow()).Type.toString();
            //if (!newValue.equals(oldValue)) {
            	actorModel.setValueAt(((JComboBox)evt.getSource()).getSelectedItem().toString(), selectedActor, ActorTableModel.columns.Type.ordinal());
            //}
        }
    }//GEN-LAST:event_typeActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        if(actorLoaded) {
            actorModel.setValueAt(name.getText(), selectedActor, ActorTableModel.columns.Name.ordinal());
        }
    }//GEN-LAST:event_nameActionPerformed

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        if(actorLoaded) {
            actorModel.setValueAt(name.getText(), selectedActor, ActorTableModel.columns.Name.ordinal());
        }
    }//GEN-LAST:event_nameFocusLost

    private void fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFocusGained
        // TODO add your handling code here:
    	if (DEBUG) { System.out.println("Focus gained on " + evt.toString()); }
    	JFormattedTextField t = (JFormattedTextField) evt.getComponent();
    	t.setText(t.getText());
    	t.selectAll();
    }//GEN-LAST:event_fieldFocusGained

public void refreshActor () {
	actorLoaded = false; // turn off property updates
	if (initTable.getSelectedRow() == -1) { return; } 
	selectedActor = initTable.getSelectedRow();
	Actor actor = actorModel.getActor(initTable.getSelectedRow());
	name.setText(actor.Name);
	switch (actor.Type) {
	case PC:
		name.setBackground(new Color(200,255,200));
		break;
	case Ally:
		name.setBackground(new Color(200,200,255));
		break;
	case Enemy:
		name.setBackground(new Color(255,200,200));
		break;
	case Neutral:
		name.setBackground(new Color(200,200,200));
		break;
	case Special:
		name.setBackground(new Color(255,200,255));
		break;
	}
	name.setForeground(new Color(0,0,0));
	switch (actor.State) {
	case Active:
		break;
	case Waiting:
		//name.setHorizontalAlignment(SwingConstants.RIGHT);
		break;
	case Disabled:
		break;
	case Unconscious:
	case Dead:
		name.setForeground(new Color(128,128,128));
		break;
	}

    status.setSelectedItem(actor.State.toString());
    type.setSelectedItem(actor.Type.toString());
    hp.setValue(((Integer)actor.HP).longValue());
    damage.setValue(((Integer)actor.Damage).longValue());
    health.setValue(((Integer)actor.Health).longValue());
	actorLoaded = true; // turn property updates back on
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_attack;
    private javax.swing.JButton add_timer;
    private javax.swing.JPanel attacks;
    private javax.swing.JFormattedTextField damage;
    private javax.swing.JFormattedTextField health;
    private javax.swing.JFormattedTextField hp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox status;
    private javax.swing.JComboBox target;
    private javax.swing.JPanel timers;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
    
	@Override
	public void tableChanged(TableModelEvent e) {
		// TODO Auto-generated method stub
		refreshActor();
	}
	
	@Override
	public void valueChanged(ListSelectionEvent e) {
		if (DEBUG) { System.out.println("List Selection event: " + e.getSource().toString()); }
		if(!e.getValueIsAdjusting()) {
			refreshActor();
		}
	}

}
